//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tektosyne {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tektosyne.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value was {0}..
        /// </summary>
        public static string ActualValue {
            get {
                return ResourceManager.GetString("ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument conflicts with value of {0} argument..
        /// </summary>
        public static string ArgumentConflict {
            get {
                return ResourceManager.GetString("ArgumentConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument specifies conflicting signs..
        /// </summary>
        public static string ArgumentConflictSign {
            get {
                return ResourceManager.GetString("ArgumentConflictSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain object with different {0}..
        /// </summary>
        public static string ArgumentContainsDifferent {
            get {
                return ResourceManager.GetString("ArgumentContainsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain an empty {0} object..
        /// </summary>
        public static string ArgumentContainsEmpty {
            get {
                return ResourceManager.GetString("ArgumentContainsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain negative values..
        /// </summary>
        public static string ArgumentContainsNegative {
            get {
                return ResourceManager.GetString("ArgumentContainsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must contain positive values..
        /// </summary>
        public static string ArgumentContainsNotPositive {
            get {
                return ResourceManager.GetString("ArgumentContainsNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain a null reference..
        /// </summary>
        public static string ArgumentContainsNull {
            get {
                return ResourceManager.GetString("ArgumentContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain a key that is a null reference..
        /// </summary>
        public static string ArgumentContainsNullKey {
            get {
                return ResourceManager.GetString("ArgumentContainsNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain a null reference or an empty object..
        /// </summary>
        public static string ArgumentContainsNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentContainsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must specify valid coordinates..
        /// </summary>
        public static string ArgumentCoordinatesInvalid {
            get {
                return ResourceManager.GetString("ArgumentCoordinatesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot equal {0}..
        /// </summary>
        public static string ArgumentEquals {
            get {
                return ResourceManager.GetString("ArgumentEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be false..
        /// </summary>
        public static string ArgumentFalse {
            get {
                return ResourceManager.GetString("ArgumentFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be greater than {0} and less than {1}..
        /// </summary>
        public static string ArgumentGreaterAndLess {
            get {
                return ResourceManager.GetString("ArgumentGreaterAndLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be greater than {0}..
        /// </summary>
        public static string ArgumentGreaterValue {
            get {
                return ResourceManager.GetString("ArgumentGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument already exists in collection..
        /// </summary>
        public static string ArgumentInCollection {
            get {
                return ResourceManager.GetString("ArgumentInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be less than {0} or greater than {1}..
        /// </summary>
        public static string ArgumentLessOrGreater {
            get {
                return ResourceManager.GetString("ArgumentLessOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be less than {0}..
        /// </summary>
        public static string ArgumentLessValue {
            get {
                return ResourceManager.GetString("ArgumentLessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be multidimensional..
        /// </summary>
        public static string ArgumentMultidimensional {
            get {
                return ResourceManager.GetString("ArgumentMultidimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be negative..
        /// </summary>
        public static string ArgumentNegative {
            get {
                return ResourceManager.GetString("ArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be divisible by {0}..
        /// </summary>
        public static string ArgumentNotDivisible {
            get {
                return ResourceManager.GetString("ArgumentNotDivisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must equal {0}..
        /// </summary>
        public static string ArgumentNotEquals {
            get {
                return ResourceManager.GetString("ArgumentNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than {0}..
        /// </summary>
        public static string ArgumentNotGreaterValue {
            get {
                return ResourceManager.GetString("ArgumentNotGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument was not found in collection..
        /// </summary>
        public static string ArgumentNotInCollection {
            get {
                return ResourceManager.GetString("ArgumentNotInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be one of these types: .
        /// </summary>
        public static string ArgumentNotInTypes {
            get {
                return ResourceManager.GetString("ArgumentNotInTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must have one of these values: .
        /// </summary>
        public static string ArgumentNotInValues {
            get {
                return ResourceManager.GetString("ArgumentNotInValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be less than array length..
        /// </summary>
        public static string ArgumentNotLessLength {
            get {
                return ResourceManager.GetString("ArgumentNotLessLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be less than {0}..
        /// </summary>
        public static string ArgumentNotLessValue {
            get {
                return ResourceManager.GetString("ArgumentNotLessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be negative..
        /// </summary>
        public static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must specify a neighboring location..
        /// </summary>
        public static string ArgumentNotNeighbor {
            get {
                return ResourceManager.GetString("ArgumentNotNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a null reference..
        /// </summary>
        public static string ArgumentNotNull {
            get {
                return ResourceManager.GetString("ArgumentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be positive..
        /// </summary>
        public static string ArgumentNotPositive {
            get {
                return ResourceManager.GetString("ArgumentNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be read-only..
        /// </summary>
        public static string ArgumentNotReadOnly {
            get {
                return ResourceManager.GetString("ArgumentNotReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an absolute file path..
        /// </summary>
        public static string ArgumentNotRooted {
            get {
                return ResourceManager.GetString("ArgumentNotRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be a null reference or an empty object..
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be positive..
        /// </summary>
        public static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument conflicts with value of {0} property..
        /// </summary>
        public static string ArgumentPropertyConflict {
            get {
                return ResourceManager.GetString("ArgumentPropertyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument contains invalid {0} property..
        /// </summary>
        public static string ArgumentPropertyInvalid {
            get {
                return ResourceManager.GetString("ArgumentPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be read-only..
        /// </summary>
        public static string ArgumentReadOnly {
            get {
                return ResourceManager.GetString("ArgumentReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument section must be large enough for collection..
        /// </summary>
        public static string ArgumentSectionLessCollection {
            get {
                return ResourceManager.GetString("ArgumentSectionLessCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument specifies invalid {0}..
        /// </summary>
        public static string ArgumentSpecifiesInvalid {
            get {
                return ResourceManager.GetString("ArgumentSpecifiesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be true..
        /// </summary>
        public static string ArgumentTrue {
            get {
                return ResourceManager.GetString("ArgumentTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type {0}..
        /// </summary>
        public static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value set to false, and Clearable is false..
        /// </summary>
        public static string BooleanFlagUnclearable {
            get {
                return ResourceManager.GetString("BooleanFlagUnclearable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Copy.
        /// </summary>
        public static string ClipboardCopy {
            get {
                return ResourceManager.GetString("ClipboardCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Copy Error.
        /// </summary>
        public static string ClipboardCopyError {
            get {
                return ResourceManager.GetString("ClipboardCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Paste.
        /// </summary>
        public static string ClipboardPaste {
            get {
                return ResourceManager.GetString("ClipboardPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Paste Error.
        /// </summary>
        public static string ClipboardPasteError {
            get {
                return ResourceManager.GetString("ClipboardPasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection contains no elements..
        /// </summary>
        public static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed-size collections cannot add or remove elements..
        /// </summary>
        public static string CollectionFixedSize {
            get {
                return ResourceManager.GetString("CollectionFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only collections cannot be modified..
        /// </summary>
        public static string CollectionReadOnly {
            get {
                return ResourceManager.GetString("CollectionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique-element collections cannot contain duplicate elements..
        /// </summary>
        public static string CollectionUnique {
            get {
                return ResourceManager.GetString("CollectionUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current value is not between {0} and {1}, and
        ///will be replaced with {0} or {1} unless corrected..
        /// </summary>
        public static string ControlRangeError {
            get {
                return ResourceManager.GetString("ControlRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value between {0} and {1}..
        /// </summary>
        public static string ControlRangeInfo {
            get {
                return ResourceManager.GetString("ControlRangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction of this type is not supported..
        /// </summary>
        public static string CtorNotSupported {
            get {
                return ResourceManager.GetString("CtorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary key was {0}..
        /// </summary>
        public static string DictionaryKey {
            get {
                return ResourceManager.GetString("DictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary key differs from object key..
        /// </summary>
        public static string DictionaryKeyMismatch {
            get {
                return ResourceManager.GetString("DictionaryKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator is not on a collection element..
        /// </summary>
        public static string EnumeratorIndex {
            get {
                return ResourceManager.GetString("EnumeratorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator invalidated by modification to collection..
        /// </summary>
        public static string EnumeratorVersion {
            get {
                return ResourceManager.GetString("EnumeratorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , column {0}.
        /// </summary>
        public static string FormatAtColumn {
            get {
                return ResourceManager.GetString("FormatAtColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at line {0}.
        /// </summary>
        public static string FormatAtLine {
            get {
                return ResourceManager.GetString("FormatAtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Code {0}).
        /// </summary>
        public static string FormatCode {
            get {
                return ResourceManager.GetString("FormatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKeyedValue key was {0}..
        /// </summary>
        public static string IKeyedValueKey {
            get {
                return ResourceManager.GetString("IKeyedValueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System physical: {0} of {1} MB available. 
        ///System virtual: {2} of {3} MB available. 
        ///Process memory: {4} of {5} MB available. .
        /// </summary>
        public static string InformationMemory {
            get {
                return ResourceManager.GetString("InformationMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection does not contain key {0}..
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string MapiAccessDenied {
            get {
                return ResourceManager.GetString("MapiAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous recipient..
        /// </summary>
        public static string MapiAmbiguousRecipient {
            get {
                return ResourceManager.GetString("MapiAmbiguousRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not found..
        /// </summary>
        public static string MapiAttachmentNotFound {
            get {
                return ResourceManager.GetString("MapiAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment open failure..
        /// </summary>
        public static string MapiAttachmentOpenFailure {
            get {
                return ResourceManager.GetString("MapiAttachmentOpenFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment write failure..
        /// </summary>
        public static string MapiAttachmentWriteFailure {
            get {
                return ResourceManager.GetString("MapiAttachmentWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipient type..
        /// </summary>
        public static string MapiBadRecipType {
            get {
                return ResourceManager.GetString("MapiBadRecipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient disk space..
        /// </summary>
        public static string MapiDiskFull {
            get {
                return ResourceManager.GetString("MapiDiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified MAPI error..
        /// </summary>
        public static string MapiFailure {
            get {
                return ResourceManager.GetString("MapiFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory..
        /// </summary>
        public static string MapiInsufficientMemory {
            get {
                return ResourceManager.GetString("MapiInsufficientMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid edit fields parameter..
        /// </summary>
        public static string MapiInvalidEditFields {
            get {
                return ResourceManager.GetString("MapiInvalidEditFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message identifier..
        /// </summary>
        public static string MapiInvalidMessage {
            get {
                return ResourceManager.GetString("MapiInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more invalid recipients..
        /// </summary>
        public static string MapiInvalidRecips {
            get {
                return ResourceManager.GetString("MapiInvalidRecips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MAPI session handle..
        /// </summary>
        public static string MapiInvalidSession {
            get {
                return ResourceManager.GetString("MapiInvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI login failure..
        /// </summary>
        public static string MapiLoginFailure {
            get {
                return ResourceManager.GetString("MapiLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message in use..
        /// </summary>
        public static string MapiMessageInUse {
            get {
                return ResourceManager.GetString("MapiMessageInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network failure..
        /// </summary>
        public static string MapiNetworkFailure {
            get {
                return ResourceManager.GetString("MapiNetworkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages found..
        /// </summary>
        public static string MapiNoMessages {
            get {
                return ResourceManager.GetString("MapiNoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported operation..
        /// </summary>
        public static string MapiNotSupported {
            get {
                return ResourceManager.GetString("MapiNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text too large..
        /// </summary>
        public static string MapiTextTooLarge {
            get {
                return ResourceManager.GetString("MapiTextTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many file attachments..
        /// </summary>
        public static string MapiTooManyFiles {
            get {
                return ResourceManager.GetString("MapiTooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many recipients..
        /// </summary>
        public static string MapiTooManyRecipients {
            get {
                return ResourceManager.GetString("MapiTooManyRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many MAPI sessions..
        /// </summary>
        public static string MapiTooManySessions {
            get {
                return ResourceManager.GetString("MapiTooManySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not supported..
        /// </summary>
        public static string MapiTypeNotSupported {
            get {
                return ResourceManager.GetString("MapiTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code..
        /// </summary>
        public static string MapiUnknown {
            get {
                return ResourceManager.GetString("MapiUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown recipient..
        /// </summary>
        public static string MapiUnknownRecipient {
            get {
                return ResourceManager.GetString("MapiUnknownRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User aborted operation..
        /// </summary>
        public static string MapiUserAbort {
            get {
                return ResourceManager.GetString("MapiUserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+.
        /// </summary>
        public static string MenuAlt {
            get {
                return ResourceManager.GetString("MenuAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+.
        /// </summary>
        public static string MenuControl {
            get {
                return ResourceManager.GetString("MenuControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+.
        /// </summary>
        public static string MenuShift {
            get {
                return ResourceManager.GetString("MenuShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} returned an invalid value..
        /// </summary>
        public static string MethodInvalidValue {
            get {
                return ResourceManager.GetString("MethodInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not implemented on abstract class..
        /// </summary>
        public static string PropertyAbstract {
            get {
                return ResourceManager.GetString("PropertyAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not implemented on derived class..
        /// </summary>
        public static string PropertyDerived {
            get {
                return ResourceManager.GetString("PropertyDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be empty..
        /// </summary>
        public static string PropertyEmpty {
            get {
                return ResourceManager.GetString("PropertyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be false..
        /// </summary>
        public static string PropertyFalse {
            get {
                return ResourceManager.GetString("PropertyFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has an invalid value..
        /// </summary>
        public static string PropertyInvalidValue {
            get {
                return ResourceManager.GetString("PropertyInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot have one of these values: .
        /// </summary>
        public static string PropertyIsInValues {
            get {
                return ResourceManager.GetString("PropertyIsInValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be {0}..
        /// </summary>
        public static string PropertyIsValue {
            get {
                return ResourceManager.GetString("PropertyIsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name: {0}.
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be negative..
        /// </summary>
        public static string PropertyNegative {
            get {
                return ResourceManager.GetString("PropertyNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be divisible by {0}..
        /// </summary>
        public static string PropertyNotDivisible {
            get {
                return ResourceManager.GetString("PropertyNotDivisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be empty..
        /// </summary>
        public static string PropertyNotEmpty {
            get {
                return ResourceManager.GetString("PropertyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must have one of these values: .
        /// </summary>
        public static string PropertyNotInValues {
            get {
                return ResourceManager.GetString("PropertyNotInValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be negative..
        /// </summary>
        public static string PropertyNotNegative {
            get {
                return ResourceManager.GetString("PropertyNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be a null reference..
        /// </summary>
        public static string PropertyNotNull {
            get {
                return ResourceManager.GetString("PropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be positive..
        /// </summary>
        public static string PropertyNotPositive {
            get {
                return ResourceManager.GetString("PropertyNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must be {0}..
        /// </summary>
        public static string PropertyNotValue {
            get {
                return ResourceManager.GetString("PropertyNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be a null reference..
        /// </summary>
        public static string PropertyNull {
            get {
                return ResourceManager.GetString("PropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be a null reference or an empty object..
        /// </summary>
        public static string PropertyNullOrEmpty {
            get {
                return ResourceManager.GetString("PropertyNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be positive..
        /// </summary>
        public static string PropertyPositive {
            get {
                return ResourceManager.GetString("PropertyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be set..
        /// </summary>
        public static string PropertySet {
            get {
                return ResourceManager.GetString("PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be set more than once..
        /// </summary>
        public static string PropertySetOnce {
            get {
                return ResourceManager.GetString("PropertySetOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be true..
        /// </summary>
        public static string PropertyTrue {
            get {
                return ResourceManager.GetString("PropertyTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search structure corrupted..
        /// </summary>
        public static string SearchStructureCorrupted {
            get {
                return ResourceManager.GetString("SearchStructureCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation succeeded..
        /// </summary>
        public static string SuccessSuccess {
            get {
                return ResourceManager.GetString("SuccessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized access is not implemented..
        /// </summary>
        public static string SynchronizedNotImplemented {
            get {
                return ResourceManager.GetString("SynchronizedNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Details:.
        /// </summary>
        public static string TechnicalDetails {
            get {
                return ResourceManager.GetString("TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot execute on foreground thread..
        /// </summary>
        public static string ThreadForeground {
            get {
                return ResourceManager.GetString("ThreadForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0} not found in type {1}..
        /// </summary>
        public static string TypeMemberNotFound {
            get {
                return ResourceManager.GetString("TypeMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found..
        /// </summary>
        public static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only views cannot be modified..
        /// </summary>
        public static string ViewReadOnly {
            get {
                return ResourceManager.GetString("ViewReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content node must be an element tag..
        /// </summary>
        public static string XmlContentNotElement {
            get {
                return ResourceManager.GetString("XmlContentNotElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content node must be an element tag named &quot;{0}&quot;..
        /// </summary>
        public static string XmlContentNotElementName {
            get {
                return ResourceManager.GetString("XmlContentNotElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content node must be empty..
        /// </summary>
        public static string XmlContentNotEmpty {
            get {
                return ResourceManager.GetString("XmlContentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content node must be simple text or CDATA block..
        /// </summary>
        public static string XmlContentNotText {
            get {
                return ResourceManager.GetString("XmlContentNotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the XML document..
        /// </summary>
        public static string XmlDocumentError {
            get {
                return ResourceManager.GetString("XmlDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML error.
        /// </summary>
        public static string XmlError {
            get {
                return ResourceManager.GetString("XmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema error.
        /// </summary>
        public static string XmlSchemaError {
            get {
                return ResourceManager.GetString("XmlSchemaError", resourceCulture);
            }
        }
    }
}
